### ISSUE TITLE
Equality check in KNN fails

### ISSUE THREAD

**Issue by bogdan-kulynych** [gchers/fbleau#7] opened 2019-11-05 16:01 UTC
It seems that the equality check in [knn.rs](https://github.com/gchers/fbleau/blob/master/src/estimates/knn.rs#L390) should be made approximate:
```
thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `Some(0.0000000000000004440892098500626)`,
 right: `Some(0.0000000000000002220446049250313)`', src/estimates/knn.rs:390:25
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
fatal runtime error: failed to initiate panic, error 5
```

**Comment by gchers** [comment] 2019-11-07 15:58
Hey @bogdan-kulynych , could you give me a train/test files that replicate the error?

(Trying to figure out if this only happens when called from the Python module, as it'd seem to appear, or not.)

**Comment by gchers** [comment] 2020-02-26 09:46
Branch #fix-assertion was solving this temporarily. However, since we cannot reproduce the error I'll close this for now. If it happens again, we'll open a new Issue.

**Closed as completed by gchers** 2020-02-26 09:46 UTC
